### ISSUE TITLE
希望优化下使用体验，谢谢

### ISSUE THREAD

**Issue by Dracl** [Samarium150/mirai-console-drift-bottle#10]
![7`4$FRJS2O_A I BP}RO3OP](https://user-images.githubusercontent.com/44107571/149626437-e66d23c8-f6e4-498b-96f2-785b8ebd96f4.png)
默认下是这样会提醒一下写了什么。
![image](https://user-images.githubusercontent.com/44107571/149626466-bf375ca1-5e07-4342-8975-edf947e504eb.png)
但是如果你把【%content】去掉，他就会报错，希望下个版本能结果这个问题，或者说自动10秒撤回也行什么的，主要是太刷屏了

以及

不显示QQ号或者群的开关，只显示QQ名字就好，现在我是编辑Reply.yml的文件来实现的，直接把变量删了~ 
但是这招对上面的【%content】没用.....

**Comment by Samarium150** [comment]
你的意思是简化回复吗

**Comment by Dracl** [comment]
是的，但是我用删变量大法，他会报错，似乎必须要那个变量才能正常运行

**Comment by Samarium150** [comment]
> 是的，但是我用删变量大法，他会报错，似乎必须要那个变量才能正常运行

是，因为这里的用法稍微有点区别。之后改一下

**Comment by Dracl** [comment]
好的，感谢
还有一个就是希望有个单独删除漂流瓶的功能，有时候傻逼群友放了些不应该放的东西，想单独删掉都无从下手，必须进去Sea.yml里面找才行，不知道有没有快捷的方法呢~

**Comment by Samarium150** [comment]
> 有时候傻逼群友放了些不应该放的东西，想单独删掉都无从下手，必须进去Sea.yml里面找才行，不知道有没有快捷的方法呢~

暂时还没有实现，并且按照现在的架构来说要实现的话稍微有点麻烦

**Comment by Dracl** [comment]
那不急~
等你把这个变量弄得能修就基本没啥没问题了，现在主要是太刷屏了

**Comment by Dracl** [comment]
或者可以添加个撤回功能，把扔漂流瓶的那条信息撤回了，这样也不怕刷屏了，还能保护是谁扔了啥~

**Comment by Samarium150** [comment]
> 或者可以添加个撤回功能，把扔漂流瓶的那条信息撤回了，这样也不怕刷屏了，还能保护是谁扔了啥~

这样不如直接私聊扔

**Comment by Dracl** [comment]
经过两天使用！
我觉得急需CD功能！！！
刷屏有点太严重了……加个群CD或者个人CD，不知道难不难呢
如果太难或者觉得没必要就算了……

**Comment by Dracl** [comment]
还有还有！！
发现居然还可以把艾特人扔进漂流瓶……
捞出来就艾特一次……超级烦人.....

**Comment by Dracl** [comment]
还遇到个问题哦~
我不清楚这个插件缓存的地方在哪，
![image](https://user-images.githubusercontent.com/44107571/149763499-c166aae6-5329-4cf7-a471-054091ca8bec.png)
我如果是这一段整条删掉，他还是会捞出来，我也把图片给删了，不知道为啥还会捞出来……(还是说漂流瓶信息不是在这)
但是如果是改信息的话 改文字，倒是可以正确生效

**Comment by Samarium150** [comment]
> 还遇到个问题哦~
> 我不清楚这个插件缓存的地方在哪，
> ![image](https://user-images.githubusercontent.com/44107571/149763499-c166aae6-5329-4cf7-a471-054091ca8bec.png)
> 我如果是这一段整条删掉，他还是会捞出来，我也把图片给删了，不知道为啥还会捞出来……(还是说漂流瓶信息不是在这)
> 但是如果是改信息的话 改文字，倒是可以正确生效

缓存确实在这里，但删除必须在console关闭的情况下操作

**Comment by Dracl** [comment]
明白了！
![N(ZP)J}GH8@5LTP@UE _`86](https://user-images.githubusercontent.com/44107571/149764144-b5bc9fca-bdbe-4324-ac70-4f41451058ef.jpg)
![F70UESR(1~E%EE4YEUAW((A](https://user-images.githubusercontent.com/44107571/149764166-84aa1873-51e2-4222-a01a-ada58e62a68e.jpg)
卧槽 猛过头了 视频和闪照tm都能丢，闪照会不会出事……

**Comment by Samarium150** [comment]
> 明白了！
> ![N(ZP)J}GH8@5LTP@UE _`86](https://user-images.githubusercontent.com/44107571/149764144-b5bc9fca-bdbe-4324-ac70-4f41451058ef.jpg)
> ![F70UESR(1~E%EE4YEUAW((A](https://user-images.githubusercontent.com/44107571/149764166-84aa1873-51e2-4222-a01a-ada58e62a68e.jpg)
> 卧槽 猛过头了 视频和闪照tm都能丢，闪照会不会出事……

说实话，没有进行安全性测试，但是除了普通的图片可以保存在本地外，其他的都是在tx的服务器上（暂时没有实现缓存功能）。如果资源过期的话应该是会报错。

**Comment by Dracl** [comment]
如果可以屏蔽掉这些就好，免得时间长了出问题，不知道视频的特征和闪照能不能屏蔽掉……
虽然可以丢闪照和视频很猛。。。

**Comment by Samarium150** [comment]
> 如果可以屏蔽掉这些就好，免得时间长了出问题，不知道视频的特征和闪照能不能屏蔽掉……
> 虽然可以丢闪照和视频很猛……
> 比如说关键词屏蔽什么的……
> 不过感觉工程量有丶大

可以在 #8 中加一个配置，`是否启用使用下一条消息作为漂流瓶内容`。关键词屏蔽的话可以启用百度内容审核。

**Comment by Dracl** [comment]
> > 如果可以屏蔽掉这些视频就好了，免得长出了问题，不知道的特征和闪照不能屏蔽掉……
> > 虽然可以闪照和视频很猛……
> > 说关键词屏蔽什么的……
> > 不过感觉工程量有丶大
> 
> 可以在#8中加一个配置，`是否启用使用下一条消息作为漂流瓶内容`。关键词屏蔽可以启用百度内容审核。

喔喔，明白了原来还可以这样，感谢~
但是这样的话，手机没办法丢漂流瓶了，毕竟手机用户是大头……
这个插件是真的棒，让群都活跃起来了~
好评！

**Comment by Samarium150** [comment]
> > 可以在#8中加一个配置，`是否启用使用下一条消息作为漂流瓶内容`。关键词屏蔽可以启用百度内容审核。
> 
> 喔喔，明白了原来还可以这样，感谢~
> 但是这样的话，手机没办法丢漂流瓶了，毕竟手机用户是大头……
> 这个插件是真的棒，让群都活跃起来了~
> 好评！

~~别关啊~~
手机用户可以使用`丢漂流瓶 <测试>`就是了，虽然图片不能用了

**Comment by Dracl** [comment]
我不太会用这个issues，不怎么懂规矩 流程 _(:3 」∠)_
是，只能丢文字了，得想个办法让他们不丢视频和闪照又不影响！

**Comment by Samarium150** [comment]
> 我不太会用这个issues，不怎么懂规矩 流程 _(:3 」∠)_

~~issue确实可以自己关，但这不是我还没实现嘛~~

> 是，只能丢文字了，得想个办法让他们不丢视频和闪照又不影响！

我考虑考虑怎么实现吧

**Comment by Dracl** [comment]
> 我考虑考虑怎么实现吧
先加CD先！
或者什么限制刷屏的手段！
扣扣你了！刷屏太严重了！但是又太有意思了！

**Comment by Samarium150** [comment]
> > 我考虑考虑怎么实现吧
> 
> 先加CD先！
> 或者什么限制刷屏的手段！
> 扣扣你了！刷屏太严重了！但是又太有意思了！

#8 合并了就有了，这两天搞定

**Comment by Dracl** [comment]
![image](https://user-images.githubusercontent.com/44107571/149911885-6eeddd67-dd75-49a6-b088-c8197cd39347.png)
再优化一个点！
就是那个Gmt+8应该是不需要显示的吧……

**Comment by Samarium150** [comment]
> 就是那个Gmt+8应该是不需要显示的吧……

确实可以，抄日期格式的时候直接用了 `yyyy-MM-dd HH:mm:ss O`

**Comment by Dracl** [comment]
想再提一个点……就不再提iss了
就是现在不是加了cd了嘛，但是不提醒他们就会以为机器人卡了……
最好加个反馈……能自定义就更好了……
可能麻烦到你了！抱歉！

**Comment by Samarium150** [comment]
> 想再提一个点……就不再提iss了
> 就是现在不是加了cd了嘛，但是不提醒他们就会以为机器人卡了……
> 最好加个反馈……能自定义就更好了……
> 可能麻烦到你了！抱歉！

@LaoLittle #13 里加个回复吧
