### ISSUE TITLE
似乎%who替换符不管用

### ISSUE THREAD

**Issue by moushicheng** [Samarium150/mirai-console-drift-bottle#19]
pickupBottle: "序号: %index\n你在海边捡到了一个来自【%who】的漂流瓶，打开瓶子，里面有一张纸条，写着：\n"

![image](https://user-images.githubusercontent.com/54257412/168776536-b5c7b5fe-b4d8-457a-b9e7-d025d1de7cb7.png)

**Comment by moushicheng** [comment]
![image](https://user-images.githubusercontent.com/54257412/168777780-694d37db-18f4-4e40-9274-b73ff757f316.png)
看了下，似乎是源码这里没考虑到别的替换符

**Comment by LaoLittle** [comment]
pr welcome
