### ISSUE TITLE
加载报错

### ISSUE THREAD

**Issue by Danwk2333** [Samarium150/mirai-console-drift-bottle#21]
加载报错，指令没有反应，但是权限能给出来
![QQ图片20220613155601](https://user-images.githubusercontent.com/106854600/173306687-df3b7b8a-2f92-4983-be8b-acd005872a0d.png)
![QQ图片20220613155619](https://user-images.githubusercontent.com/106854600/173306679-1a8e73d0-3c02-4d51-8ae0-8b6f790f5e1a.png)

**Comment by Danwk2333** [comment]
jdk-18_windows-x64_bin
mcl：2.8.2
插件用的最新的1.9.2

**Comment by Samarium150** [comment]
> mcl：2.8.2

虽然这确实是我问的mirai-console的版本，但是**mcl=mirai-console-loader≠mirai-console**

请考虑升级mirai-console，因为最新版基于2.11.1。方法可以在mcl那边看到

**Comment by Danwk2333** [comment]
好的，感谢！
