### ISSUE TITLE
重新启动mcl，放漂流瓶的文件被占用

### ISSUE THREAD

**Issue by LemonNeko2452** [Samarium150/mirai-console-drift-bottle#3]
![image](https://user-images.githubusercontent.com/56660450/146683109-0adedd06-8c34-4ff0-a38f-c3aaf998bc9b.png)

**Comment by LemonNeko2452** [comment]
删除/root/mcl-1.2.2/data/io.github.samarium150.mirai.plugin.mirai-console-drift-bottle后，漂流瓶清空

**Comment by Samarium150** [comment]
这是mirai-console`2.9.0-RC`已知的bug，不是插件的问题，请自行更新到`2.9.0-RC2`或者回滚到旧版，具体方法可以论坛看看

**Comment by LemonNeko2452** [comment]
好的，谢谢
